### ISSUE TITLE
First settings section doesn't save

### ISSUE THREAD

**Issue by wayneashleyberry** [tommcfarlin/WordPress-Settings-Sandbox#1]
Using Wordpress 3.3.1

The display options section doesn't actually save... 

Did some playing around, it definitely has something to do with > 1 sections on the same page

**Comment by tommcfarlin** [comment]
Yep - this is based on the current state of the tutorial. I cover this in the author's note and in the comments of this post[0]. We'll be running the second half of the tutorial next week and this will be resolved.

Thanks for mentioning this!

[0] http://wp.tutsplus.com/tutorials/the-complete-guide-to-the-wordpress-settings-api-part-4-on-theme-options/

**Comment by wayneashleyberry** [comment]
Do you think it's possible considering how the settings groups are currently created?

I can't see a workaround for multiple `settings_fields()` on one page

**Comment by tommcfarlin** [comment]
Yep - it's possible. I've actually already got the code written. I'll be using tabbed navigation (which is built into WordPress) that will allow for this.

**Comment by wayneashleyberry** [comment]
Cool, if you're interested I found a workaround as well
https://github.com/wayneashleyberry/WordPress-Settings-Sandbox/commit/b8d5ab31d20c8d5dd5e390b49cb12901235c00c3
