### ISSUE TITLE
how to add TinyMCE editor?

### ISSUE THREAD

**Issue by vburlak** [tommcfarlin/WordPress-Settings-Sandbox#6]
Hi, I want to add a TinyMCE editor to my Options page

I found wp_editor() function (http://codex.wordpress.org/Function_Reference/wp_editor)

But i can't make it works great in callback
And i think, i'ts wiil need custom validation, for saving HTML tags

are any solutions?

**Comment by tommcfarlin** [comment]
This is really outside the scope of the Settings Sandbox, but [this support article](http://wordpress.org/support/topic/add-new-wp_editor-to-attachment-window) may provide you with a bit more information on how to handle what you're looking for.

They are attempting to add it the attachment / media window but the principles of data sanitization and the overall process are still the same.
