### ISSUE TITLE
sandbox_theme_intialize_social_options not found

### ISSUE THREAD

**Issue by FossPrime** [tommcfarlin/WordPress-Settings-Sandbox#7]
Crash on fairly stock 3.5.1, running on local host. Crash happens immediately after activating  the theme.

Fatal error: Call to undefined function sandbox_theme_default_social_option() in /home/amama/public_html/wordpress/wp-content/themes/WordPress-Settings-Sandbox/functions.php on line 238
Call Stack
# Time    Memory  Function    Location

1   0.0007  184824  {main}( )   ../themes.php:0
2   0.0011  219796  require_once( '/home/amama/public_html/wordpress/wp-admin/admin.php' )  ../themes.php:10
3   0.1777  9976280 do_action( )    ../admin.php:111
4   0.1794  9983396 call_user_func_array ( )    ../plugin.php:406
5   0.1794  9983412 sandbox_theme_intialize_social_options( )

**Comment by FossPrime** [comment]
.... works after adding an 's' on sandbox_theme_default_social_option, so to make it sandbox_theme_default_social_options on line 238

**Comment by tommcfarlin** [comment]
Thanks! Fixed - tagged as `1.3` and sitting in `master` right now, too.

**Comment by tommcfarlin** [comment]
Thanks! Just committed 1.3 that should have resolved this. Also sitting
/master, as well.
