### ISSUE TITLE
Why reapply filter?

### ISSUE THREAD

**Issue by jcldavid** [tommcfarlin/WordPress-Settings-Sandbox#8]
On [line 175](https://github.com/tommcfarlin/WordPress-Settings-Sandbox/blob/master/functions.php#L175) It applies `sandbox_theme_default_display_options` filter when there are no display options. Then on [line 144](https://github.com/tommcfarlin/WordPress-Settings-Sandbox/blob/master/functions.php#L144), why does it re-apply the filter again?

**Comment by tommcfarlin** [comment]
The first call is responsible for initializing the default options if they don't already exist in the database. 

The second reapplies the filter by merging the user-defined options with the default options. It basically says that if the user doesn't set anything, merge the defaults array with these options

**Comment by tommcfarlin** [comment]
The first call is responsible for initializing the default options if they
don't already exist in the database.

The second reapplies the filter by merging the user-defined options with
the default options. It basically says that if the user doesn't set
anything, merge the defaults array with these options.

**Comment by jcldavid** [comment]
thank you!

**Comment by jcldavid** [comment]
Shouldn't it end up in an endless filter since the filter keeps applying `sandbox_theme_default_display_options`?

**Comment by tommcfarlin** [comment]
No - take a look at [`array_merge`](http://php.net/manual/en/function.array-merge.php) to get an idea for what's happening.

Plus, it's only invoking the `apply_filters` call once and then that function stop execution - it doesn't call anything else.

**Comment by jcldavid** [comment]
Ah, right, sorry, I got confused since the function name and the filter name's the same. Thanks again!

**Comment by jcldavid** [comment]
Hi, I'm yet again.. confused.

So first on [this line](https://github.com/tommcfarlin/WordPress-Settings-Sandbox/blob/master/functions.php#L175):

``` php
add_option(
  'sandbox_theme_display_options', 
  apply_filters( 'sandbox_theme_default_display_options', sandbox_theme_default_display_options() ) 
);
```

which applies the filters on whatever's returned here:

``` php
function sandbox_theme_default_display_options() {

        $defaults = array(
                'show_header'                =>        '',
                'show_content'                =>        '',
                'show_footer'                =>        '',
        );

        return apply_filters( 'sandbox_theme_default_display_options', $defaults );

}
```

why do we need to call `apply_filters` twice? Thank you so much, if you still have patience left :grin:.

**Comment by tommcfarlin** [comment]
No worries, @Apathetic012!

Essentially, what is happening is that any options that are _not_ set in the _Display Options_ are being set to the default array as specified in the `sandbox_theme_default_display_options`.

This initializes the database with a set of options even if the user doesn't specify them.

In the first call in  `add_options`, it's initializing the display options by calling the function `sandbox_theme_default_display_options`.

```
apply_filters( 'sandbox_theme_default_display_options', sandbox_theme_default_display_options() )
```

Then, in the `sandbox_theme_default_display_options`, it takes the array that's the defined and merges it with whatever exists. If there are options in the array, they'll be preserved; otherwise, the empty values are what will be set.
